<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>csv2zugferd.Tests</AssemblyName>
    <RootNamespace>Csv2Zugferd.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="JunitXml.TestLogger" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\csv2zugferd\csv2zugferd.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\testdata\**\*" LinkBase="testdata">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
