<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>csv2zugferd</AssemblyName>
    <RootNamespace>Csv2Zugferd</RootNamespace>
    <UseAppHost>true</UseAppHost>
    <PlatformTarget>x64</PlatformTarget>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="ZUGFeRD-csharp" />
    <PackageReference Include="ZUGFeRD.PDF-csharp" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\testdata\**\*" LinkBase="testdata">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
